### ISSUE TITLE
Korean Unicode Issue

### ISSUE THREAD

**Issue by Sihan-Son** [traff/pycharm-kr#14]
I have some korean issues.

I use Visual code as editor translate properties flies. 
But other work shown me not Korean char.
it shown to me unicode form like "\uC608\uAE30\uCE58 \uC54A\uC740 \uD30C\uC77C\uC758 \uB05D"
i want fix this problem.

i want translate same word to same word. 
but this case its very hard

**Comment by xotrs** [comment]
When you build in Korean, it looks broken. You have to build Korean by changing it to Unicode.

**Comment by traff** [comment]
To convert from Korean chars to their Unicode representation and back you can install String Manipulation plugin: https://plugins.jetbrains.com/plugin/2162-string-manipulation
(very useful plugin!)
And then use actions Escape/Unescape Java

<img width="997" alt="screen shot 2018-08-31 at 17 38 17" src="https://user-images.githubusercontent.com/1814841/44922110-bb816180-ad44-11e8-9d12-9d3522abb2aa.png">

**Comment by dodok8** [comment]
There is a similar extension for VS code. 
https://marketplace.visualstudio.com/items?itemName=mitchdenny.ecdc

Select the string you want to convert and use 'Unicode to String'.

**Comment by Sihan-Son** [comment]
Thx 
i fix it

**Comment by erishforG** [comment]
@traff

I think we have to write that "translation must be utf-16.".
