### ISSUE TITLE
Korean is steal broken

### ISSUE THREAD

**Issue by Sihan-Son** [traff/pycharm-kr#20]
i fetch from origin repo
and rebuild gradlew.bat but korean is steal broken like below link.

https://imgur.com/a/ZitxELS

**Comment by Sihan-Son** [comment]
https://drive.google.com/open?id=1zZoPLmatSqqGl3_hhSsXy2rUJkpuN8Rs

**Comment by traff** [comment]
In the comment to the issue 'Attach files by dragging & dropping...'.
But before, could you please update and rebuild it and try again - I pushed another fix, that specifies the encoding.

**Comment by Sihan-Son** [comment]
now korean is not broken it fixed
